#!/usr/bin/tcsh
if ( ! -e ~/_/i/i/axe ) then 
    echo "You have nothing you can use to break things."
#else if (  $#argv == 0 ) then 
    #echo "You must supply an object."
#else if (...) then 
    #echo "I don't know what that is."
else if ( ! -e $1 && ! -e ~/_/i/i/$1 ) then 
    echo "I don't see that here."
else if ( -e $1 && $1 != "cable" ) then 
    rm $1
    echo "Your axe breaks it into a million pieces."
else if ( -e $1 && $1 == "cable" ) then 
    echo "As you break the ethernet cable, everything starts to blur.  You collapse\nfor a moment, then straighten yourself up.\n\nConnection closed."
    exit 0
#else if (...) then 
    #echo "Your axe shatters into a million pieces."
#else 
    #echo "You take the object in your hands and swing the axe.  Unfortunately, y..."
endif
exit 1
