#!/usr/bin/tcsh
#set echo
set cutfl = "c1-4 --complement"

if ( `head -1 description` == "North end of cave passage" && $1 == "w" ) then
    echo You must type a 3 digit combination code to enter this room.
    echo -n 'Enter it here: '
    set kkk = $<
    if ( $kkk == 418 ) then
        chmod 700 w
        cd w
        if ( ! -e ~/_/i/i/lamp ) then
            grep ~/PA3/expl*Walkthrough.txt -elikely|cut -$cutfl|tee de*
            exit 1
        endif
    else
        echo Sorry, that combination is incorrect.&& exit 0
    endif
else if ( ! -e $1 && -l $1 ) then
    echo You cannot go that way. && exit 0
else
    basename `pwd` | tr "wensud" "ewsndu" | fgrep -wv $1 >& /dev/null && echo You cannot go that way. && exit 0
    cd ..
endif
head -n `ls [19]` de* && mv 9 1 >&~/X
grep -hw `ls -d * | paste ~/_/es -` -h ~/_/T*|cut -d\; -f1
exit 3
